# Generated by Django 3.2.25 on 2025-05-25 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total', models.CharField(default='5000', max_length=200)),
                ('called_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('auctioned_value', models.CharField(max_length=200)),
                ('status', models.CharField(default='unsold', max_length=200)),
                ('HUMAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournamentapp.human')),
            ],
        ),
    ]
