# Generated by Django 3.2.25 on 2025-05-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('HUMAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentapp.human')),
                ('PLAYERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentapp.players')),
            ],
        ),
    ]
