# Generated by Django 3.2.25 on 2025-05-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0002_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='name',
        ),
    ]
