# Generated by Django 3.2.25 on 2025-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0003_remove_auction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='phno',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
