# Generated by Django 3.2.25 on 2025-05-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0004_human_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='HUMAN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='tournamentapp.human'),
        ),
    ]
